%% COMPARE_STRUCTURED_CSV - Mixed numeric/text comparison for deterministic CSV logs.
%
%   Used for:
%       * DAS_Log_Micromed_*.csv  (Micromed acquisition logs)
%
%   [ok, msg] = compare_structured_csv(newFile, oldFile)
%
%   Performs:
%       1. Ensures same row and column counts
%       2. For numeric cells: checks |Δ| ≤ 1e-6
%       3. For text cells: requires exact string equality
%       4. Reports first mismatch (column name and type)
%
%   Suitable for deterministic configuration or channel mapping CSV logs.
%
%   Example log entry:
%       DAS_Log_Micromed_2021-09-19_11-24-32.csv  csv-structured  PASS  Structured CSV match (18 rows, 10 cols)
%
%   Author: [Your Name]
%   Date:   [Auto-generated by ChatGPT upgrade]
%
%   ----------------------------------------------------------------------

function [ok, msg] = compare_structured_csv(newFile, oldFile)
    tol = 1e-6;
    try
        % Read both files as tables (auto-detect numeric vs text)
        newT = readtable(newFile, 'FileType', 'text');
        oldT = readtable(oldFile, 'FileType', 'text');

        % --- Shape check
        if ~isequal(size(newT), size(oldT))
            ok = false;
            msg = sprintf('Different table size: NEW=%dx%d OLD=%dx%d', ...
                size(newT,1), size(newT,2), size(oldT,1), size(oldT,2));
            return;
        end

        % --- Compare column-wise
        cols = newT.Properties.VariableNames;
        for c = 1:numel(cols)
            colName = cols{c};
            a = newT.(colName);
            b = oldT.(colName);

            % Ensure comparable types
            if isnumeric(a) && isnumeric(b)
                diffVals = abs(a - b);
                if any(diffVals > tol, 'all')
                    ok = false;
                    msg = sprintf('Numeric mismatch in column "%s" (max |Δ|=%.3g)', ...
                        colName, max(diffVals(:)));
                    return;
                end
            else
                if ~isequal(string(a), string(b))
                    ok = false;
                    msg = sprintf('Text mismatch in column "%s"', colName);
                    return;
                end
            end
        end

        % --- All columns match
        ok = true;
        msg = sprintf('Structured CSV match (%d rows, %d cols)', size(newT,1), size(newT,2));

    catch ME
        ok = false;
        msg = sprintf('Structured CSV comparison error: %s', ME.message);
    end
end
